import { useMemo, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { Heart, LifeBuoy, Moon, ShieldCheck, Sparkles, Users, Wind, ChevronDown, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import espelhoImage from "@/assets/cuidando-espelho.jpg";

type Mood = { id: string; title: string; emoji: string; message: string; bg: string };
const moods: Mood[] = [
  { id: "exausto", title: "Exausto(a)", emoji: "🌙", message: "Você não precisa transformar exaustão em prova de força. Seu corpo está pedindo recuperação.", bg: "bg-[#E8E5F2]" },
  { id: "culpa", title: "Com culpa", emoji: "🫧", message: "Antes de se culpar, olhe também para as condições em que você precisou trabalhar e decidir.", bg: "bg-[#F4E4DF]" },
  { id: "sem-forcas", title: "Sem forças", emoji: "🌧️", message: "Você não precisa resolver tudo hoje. Escolha apenas o próximo passo seguro.", bg: "bg-[#DDEBF0]" },
  { id: "paz", title: "Em paz", emoji: "🌿", message: "Preservar o que está funcionando também é cuidado. Que bom que existe um pouco de espaço para respirar.", bg: "bg-[#E1EFE7]" },
];

const signs = [
  ["Corpo", ["Sono alterado ou dificuldade para descansar", "Fadiga ou dores persistentes", "Sensação de estar sempre em alerta", "Alterações de apetite ou energia"]],
  ["Mente", ["Dificuldade de concentração ou memória", "Pensamentos acelerados", "Trabalhar no automático", "Dificuldade maior para organizar decisões"]],
  ["Emoções", ["Irritabilidade fora do habitual", "Vazio, apatia ou perda de interesse", "Vontade de se afastar", "Sensação de não conseguir mais dar conta"]],
] as const;

const risks = [
  ["Carga e ritmo", "Excesso de tarefas, pressão contínua e pausas insuficientes podem comprometer a recuperação."],
  ["Jornada e descanso", "Turnos sucessivos, múltiplos vínculos e pouco intervalo entre jornadas reduzem o tempo de recuperação."],
  ["Relações", "Assédio, humilhação, violência e conflitos persistentes não devem ser tratados como parte normal da profissão."],
  ["Recursos e segurança", "Equipes insuficientes e condições inseguras podem afetar trabalhador e paciente."],
  ["Reconhecimento", "Autonomia, participação, respeito e reconhecimento também fazem parte de um ambiente saudável."],
];

function Reveal({ children }: { children: React.ReactNode }) {
  const reduce = useReducedMotion();
  return <motion.div initial={reduce ? false : { opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .5 }}>{children}</motion.div>;
}

function Section({ id, number, eyebrow, title, text, children }: { id: string; number: string; eyebrow: string; title: string; text: string; children: React.ReactNode }) {
  return <section id={`cqc-${id}`} className="scroll-mt-24"><Reveal><div className="mb-7 max-w-3xl"><div className="mb-3 flex items-center gap-3 text-[11px] font-black uppercase tracking-[.22em] text-[#62877A]"><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#DDEBE4] text-[#466B5F]">{number}</span>{eyebrow}</div><h2 className="font-display text-3xl font-black leading-tight text-[#17362F] sm:text-4xl lg:text-5xl">{title}</h2><p className="mt-4 text-base leading-7 text-[#61736D] sm:text-lg">{text}</p></div>{children}</Reveal></section>;
}

export function CuidandoQuemCuidaPremium() {
  const [mood, setMood] = useState<string>();
  const [selectedSigns, setSelectedSigns] = useState<string[]>([]);
  const [breathing, setBreathing] = useState(false);
  const [diary, setDiary] = useState("");
  const [community, setCommunity] = useState("");
  const [posts, setPosts] = useState(["Hoje eu percebi que levei o plantão para casa. Estou aprendendo a reconhecer quando preciso parar.", "Nem sempre é falta de vontade. Às vezes é uma equipe pequena sustentando uma demanda grande demais."]);
  const [sos, setSos] = useState(false);
  const greeting = useMemo(() => { const h = new Date().getHours(); return h < 12 ? "Bom dia. Antes de começar a cuidar, encontre um minuto para você." : h < 18 ? "Boa tarde. Como você está chegando até aqui hoje?" : "Boa noite. Se o plantão acabou, permita que seu corpo desacelere."; }, []);
  const urgency = Math.min(100, selectedSigns.length * 11);
  const toggleSign = (value: string) => setSelectedSigns(v => v.includes(value) ? v.filter(x => x !== value) : [...v, value]);
  const addPost = () => { if (!community.trim()) return; setPosts(v => [community.trim(), ...v]); setCommunity(""); };

  return <div className="relative overflow-hidden rounded-[2rem] bg-[#F7F7F1] text-[#17362F] shadow-[0_30px_100px_rgba(37,70,60,.12)] ring-1 ring-[#DCE6DF]">
    <div className="pointer-events-none absolute -left-28 top-80 h-72 w-72 rounded-full bg-[#DCEEE6]/70 blur-3xl" />
    <header className="relative min-h-[620px] overflow-hidden bg-[#183B33] sm:min-h-[700px]">
      <img src={espelhoImage} alt="Profissional de enfermagem diante de um espelho" className="absolute inset-0 h-full w-full object-cover opacity-65" />
      <div className="absolute inset-0 bg-gradient-to-b from-[#17362F]/30 via-[#17362F]/50 to-[#102B25]/95" />
      <div className="relative z-10 mx-auto flex min-h-[620px] max-w-6xl flex-col justify-between px-5 py-7 sm:min-h-[700px] sm:px-8 sm:py-10">
        <div className="flex items-center justify-between"><span className="rounded-full border border-white/20 bg-white/10 px-4 py-2 text-[10px] font-black uppercase tracking-[.2em] text-white backdrop-blur-md">Academia da Enfermagem</span><button onClick={() => setSos(true)} className="rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-bold text-white backdrop-blur-md"><LifeBuoy className="mr-1 inline h-4 w-4" /> Ajuda</button></div>
        <div className="max-w-3xl pb-6"><p className="mb-5 text-xs font-black uppercase tracking-[.25em] text-[#D6E8DF]">Um espaço para quem passa a vida cuidando</p><h1 className="font-display text-5xl font-black leading-[.95] text-white sm:text-7xl lg:text-8xl">Cuidando<br/><span className="text-[#DCEEE6]">de Quem Cuida.</span></h1><p className="mt-6 text-xl leading-8 text-white/90 sm:text-2xl">Uma viagem por dentro.<br/>Você está pronto para olhar para quem quase sempre fica por último: <strong>você?</strong></p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button onClick={() => document.getElementById("cqc-momento")?.scrollIntoView({ behavior: "smooth" })} className="h-14 rounded-2xl bg-[#DCEEE6] px-7 text-base font-black text-[#214B40] hover:bg-white"><Sparkles className="mr-2 h-5 w-5"/> Começar minha viagem</Button><Button variant="outline" onClick={() => setSos(true)} className="h-14 rounded-2xl border-white/30 bg-white/10 px-7 text-base font-bold text-white hover:bg-white/20 hover:text-white">Preciso de ajuda agora</Button></div></div>
      </div>
    </header>

    <nav className="sticky top-0 z-30 border-b border-[#DCE6DF] bg-[#F7F7F1]/90 px-3 py-2 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl gap-2 overflow-x-auto"><button onClick={() => window.scrollTo({top:0,behavior:"smooth"})} className="rounded-xl px-3 py-2 text-xs font-black text-[#55766B]">Início</button>{[["momento","Meu momento"],["sinais","Sinais"],["colo","Rede de colo"],["apoio","Apoio"],["diario","Diário"],["direitos","Direitos"]].map(([id,label]) => <button key={id} onClick={() => document.getElementById(`cqc-${id}`)?.scrollIntoView({behavior:"smooth"})} className="rounded-xl px-3 py-2 text-xs font-bold text-[#687972] hover:bg-white">{label}</button>)}<button onClick={() => setSos(true)} className="ml-auto shrink-0 rounded-xl bg-[#F2DDD8] px-3 py-2 text-xs font-black text-[#8C4D43]"><LifeBuoy className="mr-1 inline h-3.5 w-3.5"/> SOS</button></div></nav>

    <main className="relative mx-auto max-w-6xl space-y-24 px-5 py-12 sm:px-8 sm:py-16 lg:space-y-32">
      <Section id="momento" number="01" eyebrow="Meu momento" title="Como você está chegando até aqui hoje?" text="Não escolha o que você acha que deveria sentir. Escolha o que mais se aproxima de como você realmente está."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{moods.map(m => <button key={m.id} onClick={() => setMood(m.id)} className={`rounded-3xl p-5 text-left ring-1 ring-[#DCE5E0] transition hover:-translate-y-1 hover:shadow-lg ${m.bg} ${mood===m.id?"ring-2 ring-[#668B7D] shadow-lg":""}`}><span className="text-4xl">{m.emoji}</span><h3 className="mt-5 font-display text-lg font-black text-[#254A40]">{m.title}</h3><p className="mt-2 text-sm leading-6 text-[#62756E]">{mood===m.id?m.message:"Toque para receber uma mensagem de acolhimento."}</p></button>)}</div><div className="mt-6 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><Card className="rounded-3xl border-0 bg-white p-7 shadow-sm ring-1 ring-[#E1E9E4]"><div className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#F3E5D8]"><SunIcon/></div><div><p className="text-xs font-black uppercase tracking-[.15em] text-[#7E786C]">Destaque do dia · 2 minutos</p><h3 className="mt-2 text-xl font-black">Antes de entrar em casa, devolva seu corpo ao presente.</h3><p className="mt-2 text-sm leading-6 text-[#687972]">Solte os ombros. Inspire pelo nariz e solte o ar mais devagar. Observe três coisas que vê e três sons que ouve. Você não precisa levar o plantão inteiro para dentro de casa.</p></div></div></Card><Card className="rounded-3xl border-0 bg-[#DDEBE4] p-7 shadow-none"><Heart className="h-8 w-8 text-[#557A6C]"/><p className="mt-5 font-display text-2xl font-black leading-tight text-[#31594E]">Cuidar de você não diminui o cuidado que você oferece.</p></Card></div></Section>

      <Section id="sinais" number="02" eyebrow="Conhece-te por dentro" title="Seu corpo, sua mente e suas emoções também conversam com você." text="Marque o que você reconhece. Este radar ajuda a organizar a atenção; não é diagnóstico."><div className="grid gap-5 lg:grid-cols-3">{signs.map(([group,items]) => <div key={group} className="rounded-[2rem] bg-white p-6 shadow-sm ring-1 ring-[#DCE6DF]"><h3 className="font-display text-xl font-black">{group}</h3><div className="mt-5 space-y-3">{items.map(item => <button key={item} onClick={() => toggleSign(item)} className={`flex w-full gap-3 rounded-2xl p-4 text-left text-sm leading-6 transition ${selectedSigns.includes(item)?"bg-[#DDEBE4] ring-2 ring-[#719487]":"bg-[#F7F7F1] hover:bg-[#EEF3EE]"}`}><span className={`mt-1 grid h-5 w-5 shrink-0 place-items-center rounded-md border ${selectedSigns.includes(item)?"border-[#5F8476] bg-[#5F8476] text-white":"border-[#B7C8C0]"}`}>{selectedSigns.includes(item)&&<Check className="h-3 w-3"/>}</span>{item}</button>)}</div></div>)}</div><div className="mt-6 rounded-[2rem] bg-[#244A40] p-7 text-white"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#CFE4DA]">Radar de atenção</p><h3 className="mt-2 text-2xl font-black">{urgency>=70?"Seu cuidado merece prioridade.":urgency>=30?"Vale desacelerar e observar.":"Continue observando com gentileza."}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-white/75">Observe persistência, intensidade e impacto. Se os sinais estiverem piorando ou interferindo na sua vida, procure avaliação profissional.</p></div><div className="w-full md:max-w-xs"><div className="mb-2 flex justify-between text-xs"><span>atenção</span><span>{urgency}%</span></div><Progress value={urgency} className="h-3 bg-white/15"/></div></div></div></Section>

      <Section id="colo" number="03" eyebrow="Rede de colo" title="Você não é a única pessoa que já pensou “eu não estou dando conta”." text="Um mural de acolhimento para lembrar que vulnerabilidade não é incompetência."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Card className="rounded-[2rem] border-0 bg-[#E9E5F5] p-7 shadow-none"><Users className="h-8 w-8 text-[#6D6482]"/><h3 className="mt-5 font-display text-2xl font-black text-[#48405B]">Deixe um pedaço do seu plantão aqui.</h3><textarea value={community} onChange={e=>setCommunity(e.target.value)} placeholder="Escreva sem nomes ou informações identificáveis…" className="mt-5 min-h-36 w-full resize-none rounded-2xl border-0 bg-white/80 p-4 text-sm outline-none ring-1 ring-[#D4CEE2]"/><Button onClick={addPost} disabled={!community.trim()} className="mt-3 h-12 w-full rounded-2xl bg-[#625A78] font-black">Compartilhar</Button><p className="mt-3 text-center text-[11px] leading-5 text-[#6E667E]">Não inclua nomes, prontuários ou dados de pacientes.</p></Card><div className="space-y-4">{posts.map((post,i)=><Card key={`${post}-${i}`} className="rounded-3xl border-0 bg-white p-5 shadow-sm ring-1 ring-[#E1E9E4]"><div className="text-xs font-bold text-[#7A8983]">Profissional de saúde · anônimo</div><p className="mt-4 text-sm leading-7 text-[#50635C]">“{post}”</p><div className="mt-4 flex gap-2"><button className="rounded-full bg-[#F5E5E0] px-3 py-2 text-xs font-bold text-[#87584E]">🫂 Te envio um abraço</button><button className="rounded-full bg-[#E8E6F4] px-3 py-2 text-xs font-bold text-[#625A78]">💜 Te entendo</button></div></Card>)}</div></div></Section>

      <Section id="apoio" number="04" eyebrow="Apoio e fortalecimento" title="Desacelerar também é uma habilidade." text="Escolha uma prática. Não precisa fazer todas."><div className="grid gap-5 md:grid-cols-2"><Card className="rounded-[2rem] border-0 bg-[#DDEBE4] p-8 shadow-none"><Wind className="h-9 w-9 text-[#4E7668]"/><p className="mt-5 text-xs font-black uppercase tracking-[.18em] text-[#5E8275]">Respiração</p><h3 className="mt-2 font-display text-2xl font-black">Um pequeno intervalo entre você e a pressa.</h3><motion.div animate={breathing?{scale:[1,1.22,1]}:{scale:1}} transition={{duration:6,repeat:Infinity}} className="mx-auto mt-8 grid h-36 w-36 place-items-center rounded-full bg-[#BFD9CD]"><div className="grid h-24 w-24 place-items-center rounded-full bg-[#EAF4EF] text-center text-xs font-black text-[#50776A]">{breathing?"Inspire · expire":"respire"}</div></motion.div><Button onClick={()=>setBreathing(v=>!v)} className="mt-7 w-full rounded-xl bg-[#4F7769] font-black">{breathing?"Parar prática":"Começar prática"}</Button></Card><Card className="rounded-[2rem] border-0 bg-[#E9E5F5] p-8 shadow-none"><Sparkles className="h-9 w-9 text-[#6D6482]"/><p className="mt-5 text-xs font-black uppercase tracking-[.18em] text-[#77708A]">Espiritualidade</p><h3 className="mt-2 font-display text-2xl font-black">Um espaço que respeita diferentes crenças.</h3><p className="mt-4 text-base leading-8 text-[#625A70]">Você pode chamar isso de fé, oração, meditação, natureza, silêncio ou presença. O espaço é seu.</p><div className="mt-5 rounded-2xl bg-white/70 p-5 font-display text-lg font-bold leading-7 text-[#554C69]">Que eu tenha discernimento para reconhecer o que posso transformar e coragem para pedir apoio quando precisar.</div></Card></div></Section>

      <Section id="diario" number="05" eyebrow="Diário secreto" title="Deixe aqui o seu plantão." text="Escreva para organizar o que ficou preso na cabeça. O conteúdo permanece neste dispositivo."><div className="rounded-[2rem] bg-[#E7E0D5] p-6 sm:p-9"><div className="flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-[#776A5A]"/><span className="text-xs font-black uppercase tracking-[.18em] text-[#786E62]">Privado neste aparelho</span></div><textarea value={diary} onChange={e=>setDiary(e.target.value)} placeholder="O que aconteceu? O que doeu? O que você gostaria que alguém tivesse percebido?" className="mt-6 min-h-64 w-full resize-y rounded-3xl border-0 bg-[#F9F5EF]/90 p-6 font-serif text-lg leading-8 text-[#514A42] outline-none ring-1 ring-[#D6CCBE]"/><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-[#756C62]">Não escreva nomes ou informações identificáveis.</p><Button onClick={()=>setDiary("")} disabled={!diary.trim()} className="rounded-xl bg-[#6E6254] font-black">Liberar este peso</Button></div></div></Section>

      <Section id="direitos" number="06" eyebrow="Direitos, proteção e SOS" title="Cuidar de quem cuida também é proteger quem trabalha." text="Informação ajuda a reconhecer caminhos de proteção, sem substituir orientação profissional ou jurídica."><div className="grid gap-5 md:grid-cols-3"><Card className="rounded-[2rem] border-0 bg-white p-7 shadow-sm ring-1 ring-[#E1E9E4]"><ShieldCheck className="h-8 w-8 text-[#547A6C]"/><h3 className="mt-5 text-lg font-black">Documente fatos</h3><p className="mt-3 text-sm leading-7 text-[#63756E]">Registre datas, horários, situação objetiva, recursos disponíveis e impacto no trabalho. Preserve a confidencialidade dos pacientes.</p></Card><Card className="rounded-[2rem] border-0 bg-white p-7 shadow-sm ring-1 ring-[#E1E9E4]"><Heart className="h-8 w-8 text-[#7C6678]"/><h3 className="mt-5 text-lg font-black">Procure sua rede</h3><p className="mt-3 text-sm leading-7 text-[#63756E]">Converse com alguém de confiança e conheça os canais de saúde do trabalhador e apoio disponíveis no seu serviço.</p></Card><Card className="rounded-[2rem] border-0 bg-[#F2DDD8] p-7 shadow-none"><LifeBuoy className="h-8 w-8 text-[#9A554A]"/><h3 className="mt-5 text-lg font-black text-[#713E37]">Ajuda imediata</h3><p className="mt-3 text-sm leading-7 text-[#754B45]">Em uma situação de emergência, priorize segurança e procure atendimento presencial.</p><Button onClick={()=>setSos(true)} className="mt-5 rounded-xl bg-[#8C4D43] font-black">Ver caminhos</Button></Card></div></Section>

      <section className="rounded-[2.5rem] bg-gradient-to-br from-[#DDEBE4] via-[#EEF3EC] to-[#E9E5F5] p-8 text-center sm:p-14"><Sparkles className="mx-auto h-9 w-9 text-[#62877A]"/><p className="mt-5 text-xs font-black uppercase tracking-[.22em] text-[#668076]">A viagem continua</p><h2 className="mx-auto mt-3 max-w-2xl font-display text-4xl font-black leading-tight text-[#244A40] sm:text-5xl">Você cuida de tanta gente.<br/>Hoje, cuide um pouco de você.</h2><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-[#64766F]">Volte quando precisar. Não para provar que está forte, mas para lembrar que você também merece cuidado.</p></section>
    </main>

    <footer className="border-t border-[#DCE6DF] bg-white/70 px-5 py-8 text-center text-xs leading-6 text-[#718079]"><p className="font-bold text-[#557269]">Cuidando de Quem Cuida · Academia da Enfermagem</p><p>Experiência educativa. Não substitui avaliação, tratamento ou atendimento de emergência.</p></footer>

    {sos && <div className="fixed inset-0 z-[100] grid place-items-center bg-[#17362F]/60 p-4 backdrop-blur-md" onClick={()=>setSos(false)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-md rounded-[2rem] bg-[#F7F7F1] p-7 shadow-2xl"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#F2DDD8]"><LifeBuoy className="h-6 w-6 text-[#8C4D43]"/></div><h2 className="mt-5 font-display text-3xl font-black text-[#244A40]">Você não precisa passar por uma situação difícil sozinho.</h2><p className="mt-4 text-sm leading-7 text-[#63756E]">Se houver uma emergência ou risco imediato, procure atendimento presencial e acione um serviço de emergência.</p><div className="mt-6 grid grid-cols-2 gap-3"><a href="tel:192" className="rounded-2xl bg-[#F2DDD8] p-5 text-center"><span className="text-xs font-black uppercase tracking-[.15em] text-[#8C4D43]">SAMU</span><strong className="mt-1 block text-3xl text-[#713E37]">192</strong></a><a href="tel:188" className="rounded-2xl bg-[#E9E5F5] p-5 text-center"><span className="text-xs font-black uppercase tracking-[.15em] text-[#6A627B]">CVV</span><strong className="mt-1 block text-3xl text-[#554C69]">188</strong></a></div><Button onClick={()=>setSos(false)} variant="outline" className="mt-5 w-full rounded-xl">Fechar</Button></div></div>}
  </div>;
}

function SunIcon() { return <Moon className="h-6 w-6 text-[#9B7650]"/>; }
