import { useMemo, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { Heart, LifeBuoy, Moon, ShieldCheck, Sparkles, Users, Wind, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { renderContent } from "@/lib/markdown";

type Mood = { id: string; title: string; emoji: string; message: string; bg: string };
const moods: Mood[] = [
  { id: "exausto", title: "Exausto(a)", emoji: "🌙", message: "Você não precisa transformar exaustão em prova de força. Seu corpo está pedindo recuperação.", bg: "bg-[#E8E5F2]" },
  { id: "culpa", title: "Com culpa", emoji: "🫧", message: "Antes de se culpar, olhe também para as condições em que você precisou trabalhar e decidir.", bg: "bg-[#F4E4DF]" },
  { id: "sem-forcas", title: "Sem forças", emoji: "🌧️", message: "Você não precisa resolver tudo hoje. Escolha apenas o próximo passo seguro.", bg: "bg-[#DDEBF0]" },
  { id: "paz", title: "Em paz", emoji: "🌿", message: "Preservar o que está funcionando também é cuidado. Que bom que existe um pouco de espaço para respirar.", bg: "bg-[#E1EFE7]" },
];

const signs = [
  ["Corpo", ["Sono alterado ou dificuldade para descansar", "Fadiga ou dores persistentes", "Sensação de estar sempre em alerta", "Alterações de apetite ou energia"]],
  ["Mente", ["Dificuldade de concentração ou memória", "Pensamentos acelerados", "Trabalhar no automático", "Dificuldade maior para organizar decisões"]],
  ["Emoções", ["Irritabilidade fora do habitual", "Vazio, apatia ou perda de interesse", "Vontade de se afastar", "Sensação de não conseguir mais dar conta"]],
] as const;

const rights = [
  ["Sobrecarga", "Registre fatos objetivos: data, turno, equipe disponível, demanda assistencial e intercorrências. Evite exposição de pacientes e dados identificáveis."],
  ["Segurança", "Quando houver risco assistencial, siga os fluxos institucionais, comunique formalmente e preserve registros pertinentes."],
  ["Limites", "Cansaço persistente, sofrimento emocional ou prejuízo no cotidiano merecem avaliação profissional. O app não substitui atendimento clínico."],
];

function Reveal({ children }: { children: React.ReactNode }) {
  const reduce = useReducedMotion();
  return <motion.div initial={reduce ? false : { opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.12 }} transition={{ duration: 0.45 }}>{children}</motion.div>;
}

function Section({ id, number, eyebrow, title, text, children }: { id: string; number: string; eyebrow: string; title: string; text: string; children: React.ReactNode }) {
  return <section id={`cqc-${id}`} className="scroll-mt-24"><Reveal><div className="mb-7 max-w-3xl"><div className="mb-3 flex items-center gap-3 text-[11px] font-black uppercase tracking-[0.22em] text-[#62877A]"><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#DDEBE4] text-[#466B5F]">{number}</span>{eyebrow}</div><h2 className="text-3xl font-black leading-tight text-[#17362F] sm:text-4xl">{title}</h2><p className="mt-4 text-base leading-7 text-[#61736D] sm:text-lg">{text}</p></div>{children}</Reveal></section>;
}

export function CuidandoQuemCuidaPremium({ editableContent }: { editableContent?: string | null } = {}) {
  const [mood, setMood] = useState<string>();
  const [selectedSigns, setSelectedSigns] = useState<string[]>([]);
  const [breathing, setBreathing] = useState(false);
  const [diary, setDiary] = useState("");
  const [community, setCommunity] = useState("");
  const [posts, setPosts] = useState(["Hoje eu percebi que levei o plantão para casa. Estou aprendendo a reconhecer quando preciso parar.", "Nem sempre é falta de vontade. Às vezes é uma equipe pequena sustentando uma demanda grande demais."]);
  const [reactions, setReactions] = useState<Record<number, number>>({});
  const [sos, setSos] = useState(false);
  const greeting = useMemo(() => { const h = new Date().getHours(); return h < 12 ? "Bom dia. Antes de começar a cuidar, encontre um minuto para você." : h < 18 ? "Boa tarde. Como você está chegando até aqui hoje?" : "Boa noite. Se o plantão acabou, permita que seu corpo desacelere."; }, []);
  const urgency = Math.min(100, selectedSigns.length * 11);
  const toggleSign = (value: string) => setSelectedSigns(v => v.includes(value) ? v.filter(x => x !== value) : [...v, value]);
  const addPost = () => { if (!community.trim()) return; setPosts(v => [community.trim(), ...v]); setCommunity(""); };
  const releaseDiary = () => { setDiary(""); };

  return <div className="relative overflow-hidden rounded-[2rem] bg-[#F7F7F1] text-[#17362F] shadow-[0_30px_100px_rgba(37,70,60,.12)] ring-1 ring-[#DCE6DF]">
    <div className="pointer-events-none absolute -left-28 top-96 h-80 w-80 rounded-full bg-[#DCEEE6]/70 blur-3xl" />
    <header className="relative overflow-hidden bg-[#183B33] px-5 py-8 sm:px-8 sm:py-10">
      <div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-[#BFD9CF]/20 blur-3xl" />
      <div className="relative mx-auto max-w-6xl">
        <div className="flex items-center justify-between"><span className="rounded-full border border-white/20 bg-white/10 px-4 py-2 text-[10px] font-black uppercase tracking-[0.2em] text-white backdrop-blur-md">Academia da Enfermagem</span><button onClick={() => setSos(true)} className="rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-bold text-white backdrop-blur-md"><LifeBuoy className="mr-1 inline h-4 w-4" /> Ajuda</button></div>
        <div className="mt-20 max-w-4xl pb-8"><p className="mb-5 text-xs font-black uppercase tracking-[0.25em] text-[#D6E8DF]">Um espaço para quem passa a vida cuidando</p><h1 className="text-5xl font-black leading-[0.95] text-white sm:text-7xl">Cuidando<br/><span className="text-[#DCEEE6]">de Quem Cuida.</span></h1><p className="mt-6 max-w-2xl text-xl leading-8 text-white/90 sm:text-2xl">Uma viagem por dentro. Você está pronto para olhar para quem quase sempre fica por último: <strong>você?</strong></p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button onClick={() => document.getElementById("cqc-momento")?.scrollIntoView({ behavior: "smooth" })} className="h-14 rounded-2xl bg-[#DCEEE6] px-7 text-base font-black text-[#214B40] hover:bg-white"><Sparkles className="mr-2 h-5 w-5"/> Começar minha viagem</Button><Button variant="outline" onClick={() => setSos(true)} className="h-14 rounded-2xl border-white/30 bg-white/10 px-7 text-base font-bold text-white hover:bg-white/20 hover:text-white">Preciso de ajuda agora</Button></div></div>
      </div>
    </header>

    <div className="border-b border-[#DCE6DF] bg-[#F7F7F1]/95 px-3 py-2 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl gap-2 overflow-x-auto"><button onClick={() => window.scrollTo({top:0,behavior:"smooth"})} className="shrink-0 rounded-xl px-3 py-2 text-xs font-black text-[#55766B]">Início</button>{[["momento","Meu momento"],["sinais","Sinais"],["colo","Rede de colo"],["apoio","Apoio"],["diario","Diário"],["direitos","Direitos"]].map(([id,label]) => <button key={id} onClick={() => document.getElementById(`cqc-${id}`)?.scrollIntoView({behavior:"smooth"})} className="shrink-0 rounded-xl px-3 py-2 text-xs font-bold text-[#687972] hover:bg-white">{label}</button>)}<button onClick={() => setSos(true)} className="ml-auto shrink-0 rounded-xl bg-[#F2DDD8] px-3 py-2 text-xs font-black text-[#8C4D43]"><LifeBuoy className="mr-1 inline h-3.5 w-3.5"/> SOS</button></div></div>

    <main className="relative mx-auto max-w-6xl space-y-20 px-5 py-12 sm:px-8 sm:py-16 lg:space-y-28">
      {editableContent?.trim() && <section id="cqc-apresentacao"><Card className="rounded-[2rem] border-0 bg-white p-7 shadow-sm ring-1 ring-[#E1E9E4] sm:p-10"><div className="text-base leading-7 text-[#3E574F] [&_h1]:text-[#17362F] [&_h2]:text-[#17362F] [&_h3]:text-[#244A40] [&_p]:text-[#3E574F]"><div>{renderContent(editableContent)}</div></div></Card></section>}

      <Section id="momento" number="01" eyebrow="Meu momento" title="Como você está chegando até aqui hoje?" text={greeting}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{moods.map(m => <button key={m.id} onClick={() => setMood(m.id)} className={`rounded-3xl p-5 text-left ring-1 ring-[#DCE5E0] transition duration-300 hover:-translate-y-1 hover:shadow-lg ${m.bg} ${mood===m.id?"ring-2 ring-[#668B7D] shadow-lg":""}`}><span className="text-4xl">{m.emoji}</span><h3 className="mt-5 font-black text-lg text-[#254A40]">{m.title}</h3><p className="mt-2 text-sm leading-6 text-[#62756E]">{mood===m.id?m.message:"Toque para receber uma mensagem de acolhimento."}</p></button>)}</div><div className="mt-6 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><Card className="rounded-3xl border-0 bg-white p-7 shadow-sm ring-1 ring-[#E1E9E4]"><div className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#F3E5D8]"><Moon className="h-6 w-6 text-[#8A7562]"/></div><div><p className="text-xs font-black uppercase tracking-[0.15em] text-[#7E786C]">Destaque do dia · 2 minutos</p><h3 className="mt-2 text-xl font-black">Antes de entrar em casa, devolva seu corpo ao presente.</h3><p className="mt-2 text-sm leading-6 text-[#687972]">Solte os ombros. Inspire pelo nariz e solte o ar mais devagar. Observe três coisas que vê e três sons que ouve. Você não precisa levar o plantão inteiro para dentro de casa.</p></div></div></Card><Card className="rounded-3xl border-0 bg-[#DDEBE4] p-7"><Heart className="h-8 w-8 text-[#557A6C]"/><p className="mt-5 text-2xl font-black leading-tight text-[#31594E]">Cuidar de você não diminui o cuidado que você oferece.</p></Card></div></Section>

      <Section id="sinais" number="02" eyebrow="Conhece-te por dentro" title="Seu corpo, sua mente e suas emoções também conversam com você." text="Marque o que você reconhece. Este radar organiza sua atenção; não é diagnóstico."><div className="grid gap-5 lg:grid-cols-3">{signs.map(([group,items]) => <div key={group} className="rounded-[2rem] bg-white p-6 shadow-sm ring-1 ring-[#DCE6DF]"><h3 className="text-xl font-black">{group}</h3><div className="mt-5 space-y-3">{items.map(item => <button key={item} onClick={() => toggleSign(item)} className={`flex w-full gap-3 rounded-2xl p-4 text-left text-sm leading-6 transition ${selectedSigns.includes(item)?"bg-[#DDEBE4] ring-2 ring-[#719487]":"bg-[#F7F7F1] hover:bg-[#EEF3EE]"}`}><span className={`mt-1 grid h-5 w-5 shrink-0 place-items-center rounded-md border ${selectedSigns.includes(item)?"border-[#5F8476] bg-[#5F8476] text-white":"border-[#B7C8C0]"}`}>{selectedSigns.includes(item)&&<Check className="h-3 w-3"/>}</span>{item}</button>)}</div></div>)}</div><div className="mt-6 rounded-[2rem] bg-[#244A40] p-7 text-white"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#CFE4DA]">Radar de atenção</p><h3 className="mt-2 text-2xl font-black">{urgency>=70?"Seu cuidado merece prioridade.":urgency>=30?"Vale desacelerar e observar.":"Continue observando com gentileza."}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-white/75">Se os sinais forem persistentes, intensos ou estiverem interferindo na sua vida, procure avaliação profissional.</p></div><div className="w-full max-w-sm"><Progress value={urgency} className="h-3 bg-white/20"/><p className="mt-2 text-right text-xs text-white/70">Atenção atual: {urgency}%</p></div></div></div></Section>

      <Section id="colo" number="03" eyebrow="Rede de colo" title="Aqui, ninguém precisa fingir que está tudo bem." text="Um mural de apoio anônimo para transformar isolamento em reconhecimento."><div className="grid gap-6 lg:grid-cols-[1fr_.8fr]"><Card className="rounded-[2rem] border-0 bg-white p-6 shadow-sm ring-1 ring-[#DCE6DF]"><textarea value={community} onChange={e=>setCommunity(e.target.value)} placeholder="Deixe aqui uma frase sobre o seu plantão. Sem nomes, sem dados de pacientes." className="min-h-32 w-full resize-none rounded-2xl border-0 bg-[#F7F7F1] p-5 text-sm outline-none ring-1 ring-[#DCE6DF] focus:ring-2 focus:ring-[#86A99B]"/><div className="mt-4 flex justify-end"><Button onClick={addPost} className="rounded-2xl bg-[#31594E]">Compartilhar anonimamente</Button></div></Card><Card className="rounded-[2rem] border-0 bg-[#F0E9DF] p-6"><Users className="h-8 w-8 text-[#8C7864]"/><p className="mt-4 text-xl font-black text-[#4D443B]">Você não está sozinho.</p><p className="mt-2 text-sm leading-6 text-[#71675C]">Leia sem julgamento. Responda com cuidado.</p></Card></div><div className="mt-5 space-y-4">{posts.map((post,i)=><Card key={`${post}-${i}`} className="rounded-3xl border-0 bg-white p-6 shadow-sm ring-1 ring-[#E1E9E4]"><p className="text-base leading-7 text-[#3E574F]">“{post}”</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>setReactions(r=>({...r,[i]:(r[i]||0)+1}))} className="rounded-full bg-[#E7F0EB] px-4 py-2 text-xs font-bold text-[#4F7568]">🤍 Te entendo perfeitamente · {reactions[i]||0}</button><button className="rounded-full bg-[#F1E8E1] px-4 py-2 text-xs font-bold text-[#806B5B]">🫂 Te envio um abraço virtual</button><button className="rounded-full bg-[#E9E7F2] px-4 py-2 text-xs font-bold text-[#68617B]">✨ Estou torcendo por você</button></div></Card>)}</div></Section>

      <Section id="apoio" number="04" eyebrow="Apoio e fortalecimento" title="Desacelere. Respire. Volte para você." text="Ferramentas curtas para o trajeto de volta, para uma pausa e para aqueles minutos em que o mundo parece grande demais."><div className="grid gap-5 lg:grid-cols-2"><Card className="rounded-[2rem] border-0 bg-[#DDEBE4] p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#62877A]">Respiração guiada</p><h3 className="mt-2 text-2xl font-black text-[#31594E]">4 · 2 · 6</h3></div><Wind className="h-8 w-8 text-[#62877A]"/></div><div className="my-8 grid place-items-center"><motion.div animate={breathing?{scale:[1,1.22,1.22,1]}:{scale:1}} transition={breathing?{duration:12,repeat:Infinity,ease:"easeInOut"}: {duration:.3}} className="grid h-36 w-36 place-items-center rounded-full bg-white/70 ring-8 ring-white/30"><span className="text-center text-sm font-bold text-[#55766B]">{breathing?"Inspire · segure · solte":"Pronto para respirar?"}</span></motion.div></div><Button onClick={()=>setBreathing(v=>!v)} className="h-12 w-full rounded-2xl bg-[#31594E]">{breathing?"Parar exercício":"Começar respiração"}</Button></Card><Card className="rounded-[2rem] border-0 bg-[#E7E7F0] p-7"><Sparkles className="h-8 w-8 text-[#68617B]"/><h3 className="mt-5 text-2xl font-black text-[#403D50]">Reflexão de hoje</h3><p className="mt-4 text-lg leading-8 text-[#5E5A6E]">“Que eu tenha discernimento para reconhecer o que é meu, coragem para pedir apoio e gentileza comigo no caminho.”</p><p className="mt-5 text-sm text-[#777284]">Uma reflexão aberta a todas as crenças — e também a quem simplesmente precisa de um pouco de silêncio.</p></Card></div></Section>

      <Section id="diario" number="05" eyebrow="Diário secreto" title="Deixe aqui o seu plantão." text="Escreva o que você não conseguiu dizer. Este espaço é para colocar a carga para fora."><Card className="rounded-[2rem] border-0 bg-[#F0E9DF] p-6 shadow-sm ring-1 ring-[#E2D8CA] sm:p-8"><textarea value={diary} onChange={e=>setDiary(e.target.value)} placeholder="Escreva aqui. O que aconteceu? O que doeu? O que você gostaria de deixar neste espaço?" className="min-h-64 w-full resize-none rounded-3xl border-0 bg-white/75 p-6 text-base leading-7 text-[#4D443B] outline-none ring-1 ring-[#E0D5C7] focus:ring-2 focus:ring-[#B79E85]"/><div className="mt-5 flex flex-col items-center justify-between gap-4 sm:flex-row"><p className="text-sm text-[#786C60]">Nada precisa sair daqui com você.</p><Button onClick={releaseDiary} disabled={!diary.trim()} className="rounded-2xl bg-[#705B4B] px-6">🔥 Queimar e liberar</Button></div></Card></Section>

      <Section id="direitos" number="06" eyebrow="Direitos e SOS" title="Cuidar também é conhecer seus limites e proteger seu trabalho." text="Informação prática para momentos de sobrecarga, risco e sofrimento."><Accordion type="single" collapsible className="rounded-[2rem] bg-white px-6 shadow-sm ring-1 ring-[#DCE6DF]">{rights.map(([title,content],i)=><AccordionItem key={title} value={`r-${i}`}><AccordionTrigger className="text-left font-black">{title}</AccordionTrigger><AccordionContent className="leading-7 text-[#61736D]">{content}</AccordionContent></AccordionItem>)}</Accordion><div className="mt-6 grid gap-4 sm:grid-cols-3"><Card className="rounded-3xl border-0 bg-[#F2DDD8] p-6"><LifeBuoy className="h-7 w-7 text-[#8C4D43]"/><h3 className="mt-4 font-black text-[#6D3D36]">SOS emocional</h3><p className="mt-2 text-sm text-[#79534D]">Se houver sofrimento intenso ou risco imediato, procure atendimento de emergência.</p></Card><Card className="rounded-3xl border-0 bg-[#DDEBF0] p-6"><ShieldCheck className="h-7 w-7 text-[#557681]"/><h3 className="mt-4 font-black text-[#405D66]">Autoproteção ética</h3><p className="mt-2 text-sm text-[#5B7077]">Documente fatos, horários e comunicações pelos canais institucionais adequados, preservando sigilo.</p></Card><Card className="rounded-3xl border-0 bg-[#E1EFE7] p-6"><Heart className="h-7 w-7 text-[#557A6C]"/><h3 className="mt-4 font-black text-[#3E6256]">Apoio</h3><p className="mt-2 text-sm text-[#60776E]">CVV 188 oferece apoio emocional gratuito. Em emergência, procure o serviço local adequado.</p></Card></div></Section>
    </main>

    {sos && <div className="fixed inset-0 z-[100] grid place-items-center bg-[#17362F]/55 p-5 backdrop-blur-sm" role="dialog" aria-modal="true"><Card className="w-full max-w-lg rounded-[2rem] border-0 bg-[#F7F7F1] p-7 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#8C4D43]">Ajuda imediata</p><h2 className="mt-2 text-3xl font-black text-[#17362F]">Você não precisa enfrentar isso sozinho.</h2></div><button onClick={()=>setSos(false)} className="rounded-full bg-white px-3 py-2 text-sm font-bold">Fechar</button></div><div className="mt-6 space-y-3"><div className="rounded-2xl bg-[#F2DDD8] p-5"><strong>Emergência:</strong> procure o serviço de emergência local ou ligue para o número de emergência da sua região.</div><div className="rounded-2xl bg-[#E1EFE7] p-5"><strong>CVV:</strong> 188 — apoio emocional gratuito no Brasil.</div><div className="rounded-2xl bg-[#DDEBF0] p-5"><strong>Se houver risco imediato:</strong> não permaneça sozinho(a); busque uma pessoa de confiança e atendimento presencial.</div></div><Button onClick={()=>setSos(false)} className="mt-6 h-12 w-full rounded-2xl bg-[#31594E]">Voltar ao meu espaço</Button></Card></div>}
  </div>;
}
