/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtiRouteImport } from './routes/uti'
import { Route as SvPediatricoRouteImport } from './routes/sv-pediatrico'
import { Route as SvGestanteRouteImport } from './routes/sv-gestante'
import { Route as SinaisVitaisRouteImport } from './routes/sinais-vitais'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as SaudeMentalRouteImport } from './routes/saude-mental'
import { Route as RelatorioAbntRouteImport } from './routes/relatorio-abnt'
import { Route as PosturaEticaRouteImport } from './routes/postura-etica'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as ManualSobrevivenciaRouteImport } from './routes/manual-sobrevivencia'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as IrasRouteImport } from './routes/iras'
import { Route as FarmacologiaAvancadaRouteImport } from './routes/farmacologia-avancada'
import { Route as ExameFisicoEscalasRouteImport } from './routes/exame-fisico-escalas'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as CurativosRouteImport } from './routes/curativos'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AclsRouteImport } from './routes/acls'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCaktoWebhookRouteImport } from './routes/api/public/cakto-webhook'

const UtiRoute = UtiRouteImport.update({
  id: '/uti',
  path: '/uti',
  getParentRoute: () => rootRouteImport,
} as any)
const SvPediatricoRoute = SvPediatricoRouteImport.update({
  id: '/sv-pediatrico',
  path: '/sv-pediatrico',
  getParentRoute: () => rootRouteImport,
} as any)
const SvGestanteRoute = SvGestanteRouteImport.update({
  id: '/sv-gestante',
  path: '/sv-gestante',
  getParentRoute: () => rootRouteImport,
} as any)
const SinaisVitaisRoute = SinaisVitaisRouteImport.update({
  id: '/sinais-vitais',
  path: '/sinais-vitais',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudeMentalRoute = SaudeMentalRouteImport.update({
  id: '/saude-mental',
  path: '/saude-mental',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioAbntRoute = RelatorioAbntRouteImport.update({
  id: '/relatorio-abnt',
  path: '/relatorio-abnt',
  getParentRoute: () => rootRouteImport,
} as any)
const PosturaEticaRoute = PosturaEticaRouteImport.update({
  id: '/postura-etica',
  path: '/postura-etica',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualSobrevivenciaRoute = ManualSobrevivenciaRouteImport.update({
  id: '/manual-sobrevivencia',
  path: '/manual-sobrevivencia',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const IrasRoute = IrasRouteImport.update({
  id: '/iras',
  path: '/iras',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmacologiaAvancadaRoute = FarmacologiaAvancadaRouteImport.update({
  id: '/farmacologia-avancada',
  path: '/farmacologia-avancada',
  getParentRoute: () => rootRouteImport,
} as any)
const ExameFisicoEscalasRoute = ExameFisicoEscalasRouteImport.update({
  id: '/exame-fisico-escalas',
  path: '/exame-fisico-escalas',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const CurativosRoute = CurativosRouteImport.update({
  id: '/curativos',
  path: '/curativos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AclsRoute = AclsRouteImport.update({
  id: '/acls',
  path: '/acls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaktoWebhookRoute = ApiPublicCaktoWebhookRouteImport.update({
  id: '/api/public/cakto-webhook',
  path: '/api/public/cakto-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acls': typeof AclsRoute
  '/admin': typeof AdminRoute
  '/calculadora': typeof CalculadoraRoute
  '/curativos': typeof CurativosRoute
  '/diario': typeof DiarioRoute
  '/exame-fisico-escalas': typeof ExameFisicoEscalasRoute
  '/farmacologia-avancada': typeof FarmacologiaAvancadaRoute
  '/iras': typeof IrasRoute
  '/loja': typeof LojaRoute
  '/manual-sobrevivencia': typeof ManualSobrevivenciaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/postura-etica': typeof PosturaEticaRoute
  '/relatorio-abnt': typeof RelatorioAbntRoute
  '/saude-mental': typeof SaudeMentalRoute
  '/seguranca': typeof SegurancaRoute
  '/sinais-vitais': typeof SinaisVitaisRoute
  '/sv-gestante': typeof SvGestanteRoute
  '/sv-pediatrico': typeof SvPediatricoRoute
  '/uti': typeof UtiRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acls': typeof AclsRoute
  '/admin': typeof AdminRoute
  '/calculadora': typeof CalculadoraRoute
  '/curativos': typeof CurativosRoute
  '/diario': typeof DiarioRoute
  '/exame-fisico-escalas': typeof ExameFisicoEscalasRoute
  '/farmacologia-avancada': typeof FarmacologiaAvancadaRoute
  '/iras': typeof IrasRoute
  '/loja': typeof LojaRoute
  '/manual-sobrevivencia': typeof ManualSobrevivenciaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/postura-etica': typeof PosturaEticaRoute
  '/relatorio-abnt': typeof RelatorioAbntRoute
  '/saude-mental': typeof SaudeMentalRoute
  '/seguranca': typeof SegurancaRoute
  '/sinais-vitais': typeof SinaisVitaisRoute
  '/sv-gestante': typeof SvGestanteRoute
  '/sv-pediatrico': typeof SvPediatricoRoute
  '/uti': typeof UtiRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acls': typeof AclsRoute
  '/admin': typeof AdminRoute
  '/calculadora': typeof CalculadoraRoute
  '/curativos': typeof CurativosRoute
  '/diario': typeof DiarioRoute
  '/exame-fisico-escalas': typeof ExameFisicoEscalasRoute
  '/farmacologia-avancada': typeof FarmacologiaAvancadaRoute
  '/iras': typeof IrasRoute
  '/loja': typeof LojaRoute
  '/manual-sobrevivencia': typeof ManualSobrevivenciaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/postura-etica': typeof PosturaEticaRoute
  '/relatorio-abnt': typeof RelatorioAbntRoute
  '/saude-mental': typeof SaudeMentalRoute
  '/seguranca': typeof SegurancaRoute
  '/sinais-vitais': typeof SinaisVitaisRoute
  '/sv-gestante': typeof SvGestanteRoute
  '/sv-pediatrico': typeof SvPediatricoRoute
  '/uti': typeof UtiRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acls'
    | '/admin'
    | '/calculadora'
    | '/curativos'
    | '/diario'
    | '/exame-fisico-escalas'
    | '/farmacologia-avancada'
    | '/iras'
    | '/loja'
    | '/manual-sobrevivencia'
    | '/minha-conta'
    | '/postura-etica'
    | '/relatorio-abnt'
    | '/saude-mental'
    | '/seguranca'
    | '/sinais-vitais'
    | '/sv-gestante'
    | '/sv-pediatrico'
    | '/uti'
    | '/api/public/cakto-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acls'
    | '/admin'
    | '/calculadora'
    | '/curativos'
    | '/diario'
    | '/exame-fisico-escalas'
    | '/farmacologia-avancada'
    | '/iras'
    | '/loja'
    | '/manual-sobrevivencia'
    | '/minha-conta'
    | '/postura-etica'
    | '/relatorio-abnt'
    | '/saude-mental'
    | '/seguranca'
    | '/sinais-vitais'
    | '/sv-gestante'
    | '/sv-pediatrico'
    | '/uti'
    | '/api/public/cakto-webhook'
  id:
    | '__root__'
    | '/'
    | '/acls'
    | '/admin'
    | '/calculadora'
    | '/curativos'
    | '/diario'
    | '/exame-fisico-escalas'
    | '/farmacologia-avancada'
    | '/iras'
    | '/loja'
    | '/manual-sobrevivencia'
    | '/minha-conta'
    | '/postura-etica'
    | '/relatorio-abnt'
    | '/saude-mental'
    | '/seguranca'
    | '/sinais-vitais'
    | '/sv-gestante'
    | '/sv-pediatrico'
    | '/uti'
    | '/api/public/cakto-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AclsRoute: typeof AclsRoute
  AdminRoute: typeof AdminRoute
  CalculadoraRoute: typeof CalculadoraRoute
  CurativosRoute: typeof CurativosRoute
  DiarioRoute: typeof DiarioRoute
  ExameFisicoEscalasRoute: typeof ExameFisicoEscalasRoute
  FarmacologiaAvancadaRoute: typeof FarmacologiaAvancadaRoute
  IrasRoute: typeof IrasRoute
  LojaRoute: typeof LojaRoute
  ManualSobrevivenciaRoute: typeof ManualSobrevivenciaRoute
  MinhaContaRoute: typeof MinhaContaRoute
  PosturaEticaRoute: typeof PosturaEticaRoute
  RelatorioAbntRoute: typeof RelatorioAbntRoute
  SaudeMentalRoute: typeof SaudeMentalRoute
  SegurancaRoute: typeof SegurancaRoute
  SinaisVitaisRoute: typeof SinaisVitaisRoute
  SvGestanteRoute: typeof SvGestanteRoute
  SvPediatricoRoute: typeof SvPediatricoRoute
  UtiRoute: typeof UtiRoute
  ApiPublicCaktoWebhookRoute: typeof ApiPublicCaktoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uti': {
      id: '/uti'
      path: '/uti'
      fullPath: '/uti'
      preLoaderRoute: typeof UtiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sv-pediatrico': {
      id: '/sv-pediatrico'
      path: '/sv-pediatrico'
      fullPath: '/sv-pediatrico'
      preLoaderRoute: typeof SvPediatricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sv-gestante': {
      id: '/sv-gestante'
      path: '/sv-gestante'
      fullPath: '/sv-gestante'
      preLoaderRoute: typeof SvGestanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinais-vitais': {
      id: '/sinais-vitais'
      path: '/sinais-vitais'
      fullPath: '/sinais-vitais'
      preLoaderRoute: typeof SinaisVitaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saude-mental': {
      id: '/saude-mental'
      path: '/saude-mental'
      fullPath: '/saude-mental'
      preLoaderRoute: typeof SaudeMentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-abnt': {
      id: '/relatorio-abnt'
      path: '/relatorio-abnt'
      fullPath: '/relatorio-abnt'
      preLoaderRoute: typeof RelatorioAbntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postura-etica': {
      id: '/postura-etica'
      path: '/postura-etica'
      fullPath: '/postura-etica'
      preLoaderRoute: typeof PosturaEticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-sobrevivencia': {
      id: '/manual-sobrevivencia'
      path: '/manual-sobrevivencia'
      fullPath: '/manual-sobrevivencia'
      preLoaderRoute: typeof ManualSobrevivenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iras': {
      id: '/iras'
      path: '/iras'
      fullPath: '/iras'
      preLoaderRoute: typeof IrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmacologia-avancada': {
      id: '/farmacologia-avancada'
      path: '/farmacologia-avancada'
      fullPath: '/farmacologia-avancada'
      preLoaderRoute: typeof FarmacologiaAvancadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exame-fisico-escalas': {
      id: '/exame-fisico-escalas'
      path: '/exame-fisico-escalas'
      fullPath: '/exame-fisico-escalas'
      preLoaderRoute: typeof ExameFisicoEscalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curativos': {
      id: '/curativos'
      path: '/curativos'
      fullPath: '/curativos'
      preLoaderRoute: typeof CurativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acls': {
      id: '/acls'
      path: '/acls'
      fullPath: '/acls'
      preLoaderRoute: typeof AclsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cakto-webhook': {
      id: '/api/public/cakto-webhook'
      path: '/api/public/cakto-webhook'
      fullPath: '/api/public/cakto-webhook'
      preLoaderRoute: typeof ApiPublicCaktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AclsRoute: AclsRoute,
  AdminRoute: AdminRoute,
  CalculadoraRoute: CalculadoraRoute,
  CurativosRoute: CurativosRoute,
  DiarioRoute: DiarioRoute,
  ExameFisicoEscalasRoute: ExameFisicoEscalasRoute,
  FarmacologiaAvancadaRoute: FarmacologiaAvancadaRoute,
  IrasRoute: IrasRoute,
  LojaRoute: LojaRoute,
  ManualSobrevivenciaRoute: ManualSobrevivenciaRoute,
  MinhaContaRoute: MinhaContaRoute,
  PosturaEticaRoute: PosturaEticaRoute,
  RelatorioAbntRoute: RelatorioAbntRoute,
  SaudeMentalRoute: SaudeMentalRoute,
  SegurancaRoute: SegurancaRoute,
  SinaisVitaisRoute: SinaisVitaisRoute,
  SvGestanteRoute: SvGestanteRoute,
  SvPediatricoRoute: SvPediatricoRoute,
  UtiRoute: UtiRoute,
  ApiPublicCaktoWebhookRoute: ApiPublicCaktoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
