/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SvPediatricoRouteImport } from './routes/sv-pediatrico'
import { Route as SvGestanteRouteImport } from './routes/sv-gestante'
import { Route as SinaisVitaisRouteImport } from './routes/sinais-vitais'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as ProcedimentosRouteImport } from './routes/procedimentos'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as IrasRouteImport } from './routes/iras'
import { Route as EscalasRouteImport } from './routes/escalas'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCaktoWebhookRouteImport } from './routes/api/public/cakto-webhook'

const SvPediatricoRoute = SvPediatricoRouteImport.update({
  id: '/sv-pediatrico',
  path: '/sv-pediatrico',
  getParentRoute: () => rootRouteImport,
} as any)
const SvGestanteRoute = SvGestanteRouteImport.update({
  id: '/sv-gestante',
  path: '/sv-gestante',
  getParentRoute: () => rootRouteImport,
} as any)
const SinaisVitaisRoute = SinaisVitaisRouteImport.update({
  id: '/sinais-vitais',
  path: '/sinais-vitais',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosRoute = ProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const IrasRoute = IrasRouteImport.update({
  id: '/iras',
  path: '/iras',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalasRoute = EscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaktoWebhookRoute = ApiPublicCaktoWebhookRouteImport.update({
  id: '/api/public/cakto-webhook',
  path: '/api/public/cakto-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calculadora': typeof CalculadoraRoute
  '/diario': typeof DiarioRoute
  '/escalas': typeof EscalasRoute
  '/iras': typeof IrasRoute
  '/loja': typeof LojaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/seguranca': typeof SegurancaRoute
  '/sinais-vitais': typeof SinaisVitaisRoute
  '/sv-gestante': typeof SvGestanteRoute
  '/sv-pediatrico': typeof SvPediatricoRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calculadora': typeof CalculadoraRoute
  '/diario': typeof DiarioRoute
  '/escalas': typeof EscalasRoute
  '/iras': typeof IrasRoute
  '/loja': typeof LojaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/seguranca': typeof SegurancaRoute
  '/sinais-vitais': typeof SinaisVitaisRoute
  '/sv-gestante': typeof SvGestanteRoute
  '/sv-pediatrico': typeof SvPediatricoRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calculadora': typeof CalculadoraRoute
  '/diario': typeof DiarioRoute
  '/escalas': typeof EscalasRoute
  '/iras': typeof IrasRoute
  '/loja': typeof LojaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/seguranca': typeof SegurancaRoute
  '/sinais-vitais': typeof SinaisVitaisRoute
  '/sv-gestante': typeof SvGestanteRoute
  '/sv-pediatrico': typeof SvPediatricoRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calculadora'
    | '/diario'
    | '/escalas'
    | '/iras'
    | '/loja'
    | '/minha-conta'
    | '/procedimentos'
    | '/seguranca'
    | '/sinais-vitais'
    | '/sv-gestante'
    | '/sv-pediatrico'
    | '/api/public/cakto-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calculadora'
    | '/diario'
    | '/escalas'
    | '/iras'
    | '/loja'
    | '/minha-conta'
    | '/procedimentos'
    | '/seguranca'
    | '/sinais-vitais'
    | '/sv-gestante'
    | '/sv-pediatrico'
    | '/api/public/cakto-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calculadora'
    | '/diario'
    | '/escalas'
    | '/iras'
    | '/loja'
    | '/minha-conta'
    | '/procedimentos'
    | '/seguranca'
    | '/sinais-vitais'
    | '/sv-gestante'
    | '/sv-pediatrico'
    | '/api/public/cakto-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalculadoraRoute: typeof CalculadoraRoute
  DiarioRoute: typeof DiarioRoute
  EscalasRoute: typeof EscalasRoute
  IrasRoute: typeof IrasRoute
  LojaRoute: typeof LojaRoute
  MinhaContaRoute: typeof MinhaContaRoute
  ProcedimentosRoute: typeof ProcedimentosRoute
  SegurancaRoute: typeof SegurancaRoute
  SinaisVitaisRoute: typeof SinaisVitaisRoute
  SvGestanteRoute: typeof SvGestanteRoute
  SvPediatricoRoute: typeof SvPediatricoRoute
  ApiPublicCaktoWebhookRoute: typeof ApiPublicCaktoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sv-pediatrico': {
      id: '/sv-pediatrico'
      path: '/sv-pediatrico'
      fullPath: '/sv-pediatrico'
      preLoaderRoute: typeof SvPediatricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sv-gestante': {
      id: '/sv-gestante'
      path: '/sv-gestante'
      fullPath: '/sv-gestante'
      preLoaderRoute: typeof SvGestanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinais-vitais': {
      id: '/sinais-vitais'
      path: '/sinais-vitais'
      fullPath: '/sinais-vitais'
      preLoaderRoute: typeof SinaisVitaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos': {
      id: '/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof ProcedimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iras': {
      id: '/iras'
      path: '/iras'
      fullPath: '/iras'
      preLoaderRoute: typeof IrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalas': {
      id: '/escalas'
      path: '/escalas'
      fullPath: '/escalas'
      preLoaderRoute: typeof EscalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cakto-webhook': {
      id: '/api/public/cakto-webhook'
      path: '/api/public/cakto-webhook'
      fullPath: '/api/public/cakto-webhook'
      preLoaderRoute: typeof ApiPublicCaktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalculadoraRoute: CalculadoraRoute,
  DiarioRoute: DiarioRoute,
  EscalasRoute: EscalasRoute,
  IrasRoute: IrasRoute,
  LojaRoute: LojaRoute,
  MinhaContaRoute: MinhaContaRoute,
  ProcedimentosRoute: ProcedimentosRoute,
  SegurancaRoute: SegurancaRoute,
  SinaisVitaisRoute: SinaisVitaisRoute,
  SvGestanteRoute: SvGestanteRoute,
  SvPediatricoRoute: SvPediatricoRoute,
  ApiPublicCaktoWebhookRoute: ApiPublicCaktoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
