UPDATE public.mini_apps
SET content_md = REPLACE(
  REPLACE(
    content_md,
    E'<div style="background:#fffbeb; border-left:4px solid #ca8a04; border-radius:6px; padding:10px 14px; margin-bottom:12px; font-size:12.5px; color:#854d0e; line-height:1.55;">\n          <strong style="display:block; margin-bottom:4px;">🌡️ Referência de Temperatura Axilar:</strong>\n          • <strong>Afebril:</strong> 36 °C a 37,2 °C.<br>\n          • <strong>Subfebril</strong> (ainda não considerada febre): 37,3 °C a 37,7 °C.<br>\n          • <strong>Pirexia:</strong> 37,8 °C a 38,9 °C.<br>\n          • <strong>Hiperpirexia:</strong> acima de 39 °C.\n        </div>',
    E'<div style="background:#fffbeb; border-left:4px solid #ca8a04; border-radius:6px; padding:10px 14px; margin-bottom:12px; font-size:12.5px; color:#854d0e; line-height:1.55;">\n          <strong style="display:block; margin-bottom:6px;">🌡️ Referência de Temperatura Axilar — marque a faixa observada:</strong>\n          <div style="display:grid; grid-template-columns:repeat(auto-fit, minmax(220px, 1fr)); gap:6px; margin-top:4px;">\n            <label style="display:flex; align-items:center; gap:6px; padding:6px 8px; background:#ffffff; border:1px solid #fde68a; border-radius:6px; cursor:pointer;"><input type="checkbox" class="symptom" value="afebril" data-text="SINAIS GERAIS: Afebril — temperatura axilar entre 36°C e 37,2°C." style="accent-color:#166534;"><span><strong>Afebril:</strong> 36°C a 37,2°C</span></label>\n            <label style="display:flex; align-items:center; gap:6px; padding:6px 8px; background:#ffffff; border:1px solid #fde68a; border-radius:6px; cursor:pointer;"><input type="checkbox" class="symptom" value="subfebril" data-text="SINAIS GERAIS: Subfebril — temperatura axilar entre 37,3°C e 37,7°C (ainda não considerada febre)." style="accent-color:#166534;"><span><strong>Subfebril:</strong> 37,3°C a 37,7°C</span></label>\n            <label style="display:flex; align-items:center; gap:6px; padding:6px 8px; background:#fff5f5; border:1px solid #fecaca; cursor:pointer; color:#991b1b; border-radius:6px;"><input type="checkbox" class="symptom anormal" value="pirexia" data-text="SINAIS GERAIS: Pirexia — temperatura axilar entre 37,8°C e 38,9°C." style="accent-color:#b91c1c;"><span><strong>Pirexia:</strong> 37,8°C a 38,9°C</span></label>\n            <label style="display:flex; align-items:center; gap:6px; padding:6px 8px; background:#fff5f5; border:1px solid #fecaca; cursor:pointer; color:#991b1b; border-radius:6px;"><input type="checkbox" class="symptom anormal" value="hiperpirexia" data-text="SINAIS GERAIS: Hiperpirexia — temperatura axilar acima de 39°C." style="accent-color:#b91c1c;"><span><strong>Hiperpirexia:</strong> acima de 39°C</span></label>\n          </div>\n        </div>'
  ),
  E'<th style="padding: 12px 10px; font-weight: 700; color: #14532d; width: 60px; text-align: center;">ITEM</th>\n            <th style="padding: 12px 10px; font-weight: 700; color: #14532d; width: 45%;">PRESCRIÇÃO DE ENFERMAGEM COM HORÁRIO</th>\n            <th style="padding: 12px 10px; font-weight: 700; color: #14532d; width: 25%; text-align: center;">APRAZAMENTO (CHECAGEM)</th>\n            <th style="padding: 12px 10px; font-weight: 700; color: #14532d; width: 25%;">ANOTAÇÕES (TÉCNICO/AUXILIAR)</th>',
  E'<th style="padding: 12px 10px; font-weight: 700; color: #14532d; width: 60px; text-align: center;">Nº</th>\n            <th style="padding: 12px 10px; font-weight: 700; color: #14532d; width: 45%;">PRESCRIÇÃO</th>\n            <th style="padding: 12px 10px; font-weight: 700; color: #14532d; width: 20%; text-align: center;">APRAZAMENTO</th>\n            <th style="padding: 12px 10px; font-weight: 700; color: #14532d; width: 30%;">ANOTAÇÕES</th>'
)
WHERE id = 'c020e2e7-90db-449f-a508-2c173f4cada2';